sudo: required
language: go

go:
- "1.10"

env:
- CHANGE_MINIKUBE_NONE_USER=true

servervices:
  - redis-server

before_script:
# Download kubectl, which is a requirement for using minikube.
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# Download minikube.
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- sudo minikube start --vm-driver=none --kubernetes-version=v1.8.0 --extra-config=apiserver.Authorization.Mode=RBAC
# Fix the kubectl context, as it's often stale.
- minikube update-context
# Wait for Kubernetes to be up and ready.
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
# Install glide
- curl https://glide.sh/get | sh
# Redis
- sudo service redis-server start
- sudo service redis-server status
- sudo service redis-server start
- redis-cli info

jobs:
  include:
    - stage: test
      script:
        - echo "Hello from stage test"
        - telnet localhost 6379
